repos:
- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
  - id: black
    language_version: python3.7
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pyflakes
    language_version: python3.7
